import os
import yaml

def load_config():
    with open("config.yaml", "r", encoding="utf-8") as f:
        return yaml.safe_load(f)

def run():
    config = load_config()
    preview_dir = config["paths"]["preview"]
    variant = config["hero_renderer"]["default_variant"]
    username = config["project"]["username"]
    
    hero_svg_path = f"{variant}/11-hero-animated.svg"
    stats_svg_path = "12-stats.svg"
    
    readme_content = f"""<p align="center">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="preview/dinosaur-identity/11-hero-animated-dark.svg">
    <img src="preview/dinosaur-identity/11-hero-animated-light.svg" alt="Hero Animation" width="100%">
  </picture>
</p>

<h1 align="center">{username}</h1>
<p align="center"><strong>Building Resilient Systems • Applied AI Security • Threat Detection Engineering</strong></p>

---

## 🏗️ WHAT I'M BUILDING

I engineer systems that break less and catch threats faster. My work focuses on the practical intersection of high-performance architectures, machine learning, and offensive security research. If a system is complex, I want to understand how it fails—and build the tooling to prevent it.

**Currently working on:**
- **[Baryonyx](https://github.com/{username}/Baryonyx)**: Application attack-surface discovery and offensive web reconnaissance.
- **[SentinelMesh](https://github.com/{username}/SentinelMesh)**: Security/compliance architecture and cross-system security engineering.
- **[Insider-Threat-Detection](https://github.com/{username}/Insider-Threat-Detection)**: ML-based behavioral analysis for insider-threat detection.

---

## 📊 RECENT ACTIVITY

<p align="left">
  <img src="preview/{stats_svg_path}" alt="{username}'s GitHub Statistics">
</p>

---

## ⚙️ UNDER THE HOOD

This entire GitHub profile is deterministically generated by a custom offline CI pipeline. The terminal-style robotic dinosaur hero image above is automatically mapped from a source PNG into a multi-layered ASCII SVG, utilizing Canny edge detection and HSV masking, and then animated via sequential SVG clip-path reveals.

You can inspect the generator code here: **[GitHub Profile Generator](https://github.com/{username}/{username})**

---

## 📡 COMM LINK

Feel free to explore my repositories or open an issue if you want to collaborate on security tooling or system architecture.
"""

    readme_path = "README.md"
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(readme_content)
    print(f"Assembled final README at {readme_path}")

if __name__ == "__main__":
    run()
